// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzgiw7mhEsiTfYqnYEwP72-U0Rfq8oAww',
    appId: '1:122392581066:web:e3e080c01a7d068021b533',
    messagingSenderId: '122392581066',
    projectId: 'cicero-8141b',
    authDomain: 'cicero-8141b.firebaseapp.com',
    storageBucket: 'cicero-8141b.firebasestorage.app',
    measurementId: 'G-33DG0BWJWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRV7ChO83ZODyqCUHbsTYMzdOM22j-7Vo',
    appId: '1:122392581066:android:b50a9c98e170c83e21b533',
    messagingSenderId: '122392581066',
    projectId: 'cicero-8141b',
    storageBucket: 'cicero-8141b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMcVYowg2D5wckk2aClZtv4aAoaLQQXWk',
    appId: '1:122392581066:ios:372f88e1eeab32d721b533',
    messagingSenderId: '122392581066',
    projectId: 'cicero-8141b',
    storageBucket: 'cicero-8141b.firebasestorage.app',
    iosClientId: '122392581066-h9f6qi01cupk8c7c5l2jr775cr54hcgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciceroApp',
  );

}